### ISSUE TITLE
not correctly determining node vs. browser

### ISSUE THREAD

**Issue by bgrayburn** [Axinom/x2js#45]
For a production webpack build (not sure at the moment why it only happens in prod) x2js was only able to properly discern the environment was node when the `if`(ln 37) and first `else if`(41) clauses were swapped. Would this cause errors in other environments? Would you accept a pull request for this?

**Comment by sandersaares** [comment]
Interesting. This project uses the fairly common UMD pattern for its modular definition (https://github.com/umdjs/umd/blob/master/templates/returnExports.js). Perhaps it might be better to file an issue with webpack, as I understand it includes some intricate module packaging logic that may be operating suboptimally here. Just speculating, though - I do not really feel sufficient qualified to understand the intricacies of module packaging but since UMD is a fairly common thing, I would place the first suspicion at webpack.

**Comment by sandersaares** [comment]
Closing as it seems not an x2js issue and no further information has been added in a while.
